import type { Metadata } from "next";
import { Geist, Geist_Mono, Merriweather_Sans } from "next/font/google";
import "./globals.css";
import Aurora from "@/components/Aurora";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const merriweather = Merriweather_Sans({
  subsets: ["latin"],
  weight: ["800", "600"],
});

export const metadata: Metadata = {
  title: "ENS Pin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${merriweather.className} antialiased`}>
        <div className="absolute inset-0 -z-10">
          <Aurora 
          colorStops={["#94B0FF", "#3A29FF", "#DDF7FF"]}
          blend={0.5}
          amplitude={1.0}
          speed={0.5}
          />
        </div>
        {children}
      </body>
    </html>
  );
}
